server:
  port: 8089
spring:
  application:
    name: "Movie Review"
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true

  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false

  #====================== Mail Config
  mail:
    host: smtp.gmail.com
    username: gwinbleid86@gmail.com
    password: "lfxd cbqc tyhf nehe"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #====================== Mail Config



  #====================== OAuth2.0 Config
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
#====================== OAuth2.0 Config


logging:
  level:
    root: info
    org:
      hibernate:
        type: error
        stat: error
      springframework:
        security: info
    web: info
    sql: error
  file:
    path: logs
