name: Deployment to server

on:
  workflow_dispatch
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{ github.actor }}/movie_review_java_23:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload artifact
      uses: echapmanFromBunnings/upload-artifact@3.0
      with:
        name: 'artifact'
        path: ./target/movie_review*.jar
        retention-days: 1

  publish:
    needs: build
    name: Publish image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: echapmanFromBunnings/download-artifact@3.0
        with:
          name: 'artifact'

      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Publish docker image
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMG_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMG_NAME }}

  deploy:
    needs: publish
    name: Deploy Image

    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and pull docker image
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull
            docker compose up -d
            exit